// Generated by CoffeeScript 1.7.1
(function() {
  var changeStatusLine;

  $(function() {
    $('.change-block').click(function(e) {
      var id;
      id = $(this).parents('.container').attr('id');
      changeStatusLine('event:changeBlock()=' + id);
    });
    $('.small-picture').click(function(e) {
      var img, src;
      img = $(this).parents('.container').find('.big-picture');
      src = $(this).find('img').attr('src');
      img.attr('src', src);
    });
  });

  changeStatusLine = function(status) {
    window.status = status;
    window.status = "done";
  };

}).call(this);
