// Generated by CoffeeScript 1.7.1
(function() {
  $(function() {
    $.cookie("tinyEditor", 1);
    $('.small-picture').click(function(e) {
      var img, src;
      img = $('.small-picture').parents('.container').find('.big-picture');
      src = $(this).find('img').attr('src');
      img.attr('src', src);
    });
  });

}).call(this);
